### ISSUE TITLE
KoolCenter 规划以及问题答疑

### ISSUE THREAD

**Issue by jannson** [koolshare/koolcenter#1]
为了减少大家的猜测，这里给大家介绍下 KoolCenter 下一步的计划，以及回答部分大家关注的问题。

## KoolCenter 规划

KoolCenter 需要全新开发，我们并没有直接利用的第三方开源平台，我们会逐步开发成我们满意的效果。可能的内容如下：

1. 增加各种文档，包括所有插件的教程，最佳实践等。希望酷友们养成看文档的习惯
2. 增加用户体系
3. 用户可以投稿（但是对文章质量要求比较高）
4. 提供更专业的问答专区，解决大家刷固件，使用软件，使用场景的问题。并且会把常用问题整理到文档中，减少过多的垃圾问题
5. VIP 服务（这一块先保持神秘，它能保证更多牛人来发布文章，开发插件，回答用户的问题，并且从中得到应有的利益）

当然在这期间，我们会持续更新软件中心，固件等。

毕竟已经是多年的老朋友了，请大家继续信任，支持我们！

### 新站啥时候开啊，中间会不会有空档期？
新站也开，就是 https://www.koolcenter.com 可能会有一定的空档期，但是不会影响大家固件的使用。

### 感觉搬家后没有”社区“功能了？
对。我们会弱化社区，强化问答。

### 是否更加商业化了
考虑到之前几乎没商业化，未来肯定比之前更商业化。但我们永远不会强买强卖。
并且固件永远是免费的，且固件都带着软件中心，插件的教程、评测肯定也是免费的。
请大家不要过多担心商业化的问题，并且新的网站新的开始，网站没做好，商业化就不会开始。

### 没有社区，好多朋友写的特别好的教程，不知道会放在哪里？
我们会安排迁移，以后新的好文，可以通关投稿的方式发布，发布审核之后，教程会被存到 https://github.com/koolshare/koolcenter 。我们工作人员也会长期维护这个教程，保证教程持续生效。

### 觉得应该加上社区功能，这样更方便大家讨论，对于反馈一些 BUG 和解决 BUG 也更有利
我们会有更好的问答专区，对问题进行分类，方便大家邀请别人来回答问题

### 新版的没社区，说是不忘初心，但是个人都嗅到了那种味道，但不必担心，一鲸落，万物生
此话阴阳怪气，看不懂。

### 固件下载还会是免费的吗？会扫码下载吗？
免费，不会，请大家放心。

其它问题请在下方留言。

**Comment by sheip9** [comment]
各文章下会开放留言或评论吗

**Comment by jannson** [comment]
文章开放留言跟评论，这个我们还没想好！

**Comment by hanjian53793623** [comment]
交流这块 放在哪里呢？

**Comment by jannson** [comment]
问答区，还在开发中

**Comment by kotonamihuiren** [comment]
希望固件尽快补齐吧 今天刚到的网件RAX80找不到梅林固件了

**Comment by jannson** [comment]
好的，收到。

**Comment by r0ckrise** [comment]
请问还有办法查看之前论坛上大佬发布的教程吗？想看一篇esxi7安装到u盘的教程看不到了，搞不定现在。

**Comment by jannson** [comment]
> 请问还有办法查看之前论坛上大佬发布的教程吗？想看一篇esxi7安装到u盘的教程看不到了，搞不定现在。

需要等一段时间，后续我们会以历史数据的形式重新开发。最近一些天还不行

**Comment by jannson** [comment]
> 希望固件尽快补齐吧 今天刚到的网件RAX80找不到梅林固件了

RAX80 网站更新了相关固件教程。可以看看

**Comment by r0ckrise** [comment]
好的，谢谢> > 请问还有办法查看之前论坛上大佬发布的教程吗？想看一篇esxi7安装到u盘的教程看不到了，搞不定现在。
> 
> 
> 
> 需要等一段时间，后续我们会以历史数据的形式重新开发。最近一些天还不行

**Comment by r0ckrise** [comment]
好的，谢谢
> 
> 
> 
> 需要等一段时间，后续我们会以历史数据的形式重新开发。最近一些天还不行

**Comment by xmasrain** [comment]
纯粹的个人看法，应该等大部分功能都做好了再上线新网站，现在弄个半成品就赶鸭子上架，既影响用户体验，又损失一波用户。

**Comment by jannson** [comment]
> 纯粹的个人看法，应该等大部分功能都做好了再上线新网站，现在弄个半成品就赶鸭子上架，既影响用户体验，又损失一波用户。

道理是这么个道理，谁也不想折腾。

**Comment by aoxue** [comment]
新网站迁移正常不都是一般都是在论坛上发布内测，新老共存一段时间然后再切啊。现在一刀切，新的又没有弄好，这样很不友好，一下子连个“家”都没有了，感觉很失望。

其实这种靠修改固件优化发展起来的论坛，最重要的就是用户使用感受之间讨论，现在直接把最重要的部分切掉，真的很不合适。如果真的想商业化，可以参考威锋等论坛的改造。威锋虽然现在也在艰难的改革，但是人家当初迁移到新的模式的时候至少做得比KoolCenter好很多。
其实类似这种论坛，最重要的还是用户，而不是固件、软件，再好再优秀固件，也是需要依靠用户来使用的，如果用户不能第一时间反馈自己的感受，这个是做不长久的，论坛的讨论才是带来流量的最主要的核心点，而不是你们之后提到的问答模式。

纯粹个人小小意见，不喜勿喷。

**Comment by jannson** [comment]
感谢提供这么好的建议。
写得这么细致，我能感受到，所以我也认真的回复你。当需要一刀切的时候，其实已经是没有办法的办法了。
玩家交流会让网站有温度，让兴趣一致的人们有个家，这个谁都能理解的。
我们把玩家交流割舍掉，要做好产品跟问答，最主要考虑的就是投入成本。这个成本在哪里？—— 光审核，这个成本就很高。

说不好听的，我们之所以在坚持，是因为当初一帮兄弟靠激情建设起来的东西，不希望白费掉。削减成本是目前一个核心问题。

我们不希望把工作跟时间投入在审核帖子等等上面，这个很贵，并且用户的体验也不好。

回到 6 年前我个人最初的想法，论坛只不过是我发布固件，收集固件 BUG 的地方。我只不过从新专注于我最初想做的事情。

那即使论坛没有了，我需要的也只不过是固件发布，收集用户问题，解决用户问题的地方。如果大家愿意互相交流，可以在 QQ 群，或者其他论坛去交流。

**Comment by jannson** [comment]
没问题的。等等

**Comment by nimasi** [comment]
以前帖子的存档也没了吗，很多问答都是很有帮助的，现在连个快照都没了

**Comment by szxhzz** [comment]
梅林改版下面没有AC86U板块了

**Comment by jannson** [comment]
> 收藏了几个openwrt的帖子都没了。。

说了会回来的，时间问题。

**Comment by simear2004** [comment]
没有社区讨论，固件感觉都不香了，有同感的没？

**Comment by ymgz12890** [comment]
其实论坛关了倒也有好处，这几年明显感觉越来越严了，讨论固件的时候很多人都会提到梯子之类的事情，影响太大了容易被盯上。社区是个挺危险的东西，现在越来越重视网络舆情了，一直靠审核也不是办法。人在国内的话还是悠着点

**Comment by jannson** [comment]
> 建议访问以前的老域名给个重定向或者自动跳转 到新站，不然老用户看到403很迷茫。

没办法，目前我们只能返回 403，非技术问题。

**Comment by jannson** [comment]
380 软件中心还在。

**Comment by byyxx128** [comment]
为了避免把成本都投入到审核贴子中而关闭社区，这一点完全可以理解。不过建议把这一条写到最上面的 FAQ 里面吧，不然很多人（包括曾经的我）都以为初心变了……实际上这都是没有办法的办法。像比如 IT 之家，就曾经因为评论区的事直接把关评了，直到今天依然是评论审核后显示，且只显示最近一周的评论，但 IT 之家毕竟还是个商业网站，能雇专人来审核。咱这个确实不行，不能把成本浪费在这个上面。

另外上面有一句说的“一鲸落，万物生”不是阴阳怪气，这是网友以为你们初心泯灭了在讽刺你们……但这不怪网友，怪你们没说清这个事。你就把我前面说的这一条写明就行，你就明说是因为没有成本去审核帖子，就完了。这样大家就都懂了。百度贴吧都曾经把历史帖子全部隐藏了……想想吧，每年因为审核，各大平台要浪费掉多少人力资金，这还不算，一旦有一个漏网之鱼，直接关站整顿……所以，在网友素质普遍提高之前，关社区确实是最好办法了。这一点只要写明了大家都能理解。主要还是没说清楚这个事。

**Comment by byyxx128** [comment]
为了避免把成本都投入到审核贴子中而关闭社区，这一点完全可以理解。不过建议把这一条写到最上面的 FAQ 里面吧，不然很多人（包括曾经的我）都以为初心变了……实际上这都是没有办法的办法。像比如 IT 之家，就曾经因为评论区的事直接把关评了，直到今天依然是评论审核后显示，且只显示最近一周的评论，但 IT 之家毕竟还是个商业网站，能雇专人来审核。咱这个确实不行，不能把成本浪费在这个上面。

另外上面有一句说的“一鲸落，万物生”不是阴阳怪气，这是网友以为你们初心泯灭了在讽刺你们……但这不怪网友，怪你们没说清这个事。你就把我前面说的这一条写明就行，你就明说是因为没有成本去审核帖子，就完了。这样大家就都懂了。百度贴吧都曾经把历史帖子全部隐藏了……想想吧，每年因为审核，各大平台要浪费掉多少人力资金，这还不算，一旦有一个漏网之鱼，直接关站整顿……所以，在网友素质普遍提高之前，关社区确实是最好办法了。这一点只要写明了大家都能理解。主要还是没说清楚这个事。
***
补充解释下，“一鲸落，万物生”是说，鲸在知道自己寿尽的时候，会一跃进入大海，然后其尸体会被分解回归大自然，进而可以滋养更多生命。换句话说就是：一个XX倒下去，千万个XX站起来。这个纯粹是网友误以为你们不干了……真的不是阴阳怪气。
