### ISSUE TITLE
固件下载页面内容尚未修改

### ISSUE THREAD

**Issue by sheip9** [koolshare/koolcenter#2]
此页面内容未删除原hugo的自带内容，麻烦记得弄下
https://github.com/koolshare/koolcenter/blob/main/content/zh/firmware/6_download/_index.md
对应链接https://koolcenter.com/article/firmware/6_download/

**Comment by jannson** [comment]
好的，我让 S 大把所有的固件下载信息都迁移过来，他还没有迁移。我会尽快让他在国庆期间弄好。

**Comment by jannson** [comment]
今天更新了不少固件教程：https://www.koolcenter.com/article/firmware/6_download/official_mod/

**Comment by sheip9** [comment]
![图片](https://user-images.githubusercontent.com/53911290/135702549-11dae6a7-6e88-46fa-8cc8-9b2a8ce2ab43.png)

**Comment by jannson** [comment]
好了，又大更新了一波。
