### ISSUE TITLE
梅林改版下面没有AC86U板块了

### ISSUE THREAD

**Issue by szxhzz** [koolshare/koolcenter#7]
梅林改版下面没有AC86U板块了

**Comment by jannson** [comment]
收到

**Comment by sadoneli** [comment]
已经添加：https://www.koolcenter.com/article/firmware/6_download/merlin_mod/64_rt-ac86u_merlin_mod/

源码：https://github.com/koolshare/koolcenter/blob/main/content/zh/firmware/6_download/merlin_mod/64_RT-AC86U_merlin_mod.md
